<?php

/**
 * @file
 *  Contains date wizard hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function date_tools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'date_tools.admin':
      return '<p>' . t('<h2>Tools for Dates and Calendars</h2>') . '</p>';
    case 'admin/config/date/tools/date_wizard':
      $output = t("Fill out the following form to auto-create a date content type, with a datetime field and matching pre-configured calendar. If the calendar module is enabled and the option to create a calendar is chosen, a calendar and upcoming events block will be created, an ical feed will be added to the calendar. Nodes created from this new content type will include a link to the calendar, and the calendar will have a link to the 'add new date' form. You can also add new date fields to an existing content type by entering the existing content type name instead of creating a new one.");
      $output .= '</p><p>';
      $output .= t('Only a limited set of options are displayed here to make this easy to set up. Once the date has been created you will be able to make other changes to the date settings and add other fields to your new content type on the Manage fields screen. You can also make changes to the calendar on the Views edit page.');
      $output .= '</p>';
      return $output;
  }
}
